#!/usr/bin/env bash

PID_FILE="/tmp/myscript.pid"

# PID dosyası oluştur
echo $$ > "$PID_FILE"

# SIGTERM
handle_sigterm() {
    echo "I hate the kill command"
    rm -f "$PID_FILE"
    exit 0
}

# SIGINT
handle_sigint() {
    echo "Y U no love me?!"
}

# SIGQUIT
handle_sigquit() {
    rm -f "$PID_FILE"
    exit 0
}

trap handle_sigterm TERM
trap handle_sigint INT
trap handle_sigquit QUIT

while true
do
    echo "To infinity and beyond"
    sleep 1
done
