#!/usr/bin/env bash
# process and pid file
PID_FILE="/var/run/myscript.pid"

if [ ! -f "$PID_FILE" ]; then
    touch "$PID_FILE"
fi

chmod 666 "$PID_FILE"
echo $$ > "$PID_FILE"

trap 'echo "I hate the kill command"; rm -f "$PID_FILE"; exit 0' TERM
trap 'echo "Y U no love me?!";' INT
trap 'rm -f "$PID_FILE"; exit 0' QUIT

while true
do
    echo "To infinity and beyond"
    sleep 1
done
